const String SUPABASE_URL = 'https://chnpqmnrxqmahwxhorir.supabase.co';
const String SUPABASE_ANON_KEY =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNobnBxbW5yeHFtYWh3eGhvcmlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5OTEzNzQsImV4cCI6MjA0OTU2NzM3NH0.0uNZJHXhLcrDs4JqDdI3m7kTM9BxKeN5JARNIfmb1OA';
